# *******************************************************************
# This file was created automatically by the sample environment
# generator. Developers should use `tox -e genconfig` to update it.
# Users are recommended to make changes to a copy of the file instead
# of the original, if any customizations are needed.
# *******************************************************************
# title: Configuration for Routed Networks
# description: |
#   Contains the available parameters that need to be configured when using
#   a routed networks environment. Requires the routed-networks.yaml or
#   routed-networks-ipv6.yaml environment.
parameter_defaults:
  # The IP addresses of DHCP servers to relay DHCP requests to.
  # Mandatory. This parameter must be set by the user.
  # Type: json
  dhcp_ips: <None>

  # The Nova flavor to use for the dhcrelay instance
  # Type: string
  dhcp_relay_flavor: m1.small

  # The base image for the dhcrelay instance.  A CentOS 7 image is currently
  # the only one supported.
  # Type: string
  dhcp_relay_image: CentOS-7-x86_64-GenericCloud

  # DHCP relay address on the provision2 network subnet
  # Type: string
  dhcp_relay_provision2_address: 192.168.25.253

  # DHCP relay address on the provision3 network subnet
  # Type: string
  dhcp_relay_provision3_address: 192.168.26.253

  # DHCP relay address on the provision network subnet
  # Type: string
  dhcp_relay_provision_address: 192.168.24.253

  # Prefix for the name of the dhcrelay instance
  # Type: string
  dhcrelay_prefix: dhcrelay

