heat_template_version: 2015-10-15

parameters:

  undercloud_name:
    type: string

  private_net:
    type: string

  networks:
    type: json

resources:
  undercloud_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        list_join:
        - '_'
        - - {get_param: undercloud_name}
          - 'sg'
      description: Ping, SSH, and TripleO UI
      rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
      - protocol: tcp
        port_range_min: 3000
        port_range_max: 3000

  private_undercloud_port:
    type: OS::Neutron::Port
    properties:
      name:
        list_join:
        - '_'
        - - {get_param: undercloud_name}
          - 'private'
      network: {get_param: private_net}
      security_groups:
      - {get_resource: undercloud_sg}

  provision_undercloud_port:
    type: OS::Neutron::Port
    properties:
      name:
        list_join:
        - '_'
        - - {get_param: undercloud_name}
          - 'provision'
      network: {get_param: [networks, provision]}
      port_security_enabled: False

  public_undercloud_port:
    type: OS::Neutron::Port
    properties:
      name:
        list_join:
        - '_'
        - - {get_param: undercloud_name}
          - 'public'
      network: {get_param: [networks, public]}
      port_security_enabled: False

outputs:
  ports:
    value:
    - {port: {get_resource: private_undercloud_port}}
    - {port: {get_resource: provision_undercloud_port}}
    - {port: {get_resource: public_undercloud_port}}
  addresses:
    value:
      private_undercloud: {get_attr: [private_undercloud_port, fixed_ips, 0, ip_address]}
      provision_undercloud: {get_attr: [provision_undercloud_port, fixed_ips, 0, ip_address]}
      public_undercloud: {get_attr: [public_undercloud_port, fixed_ips, 0, ip_address]}
