heat_template_version: 2015-04-30

parameters:
  provision_net:
    type: string
    default: provision
    description: Name of a network that will be used for provisioning traffic

  provision_net_cidr:
    type: string
    description: CIDR for provision network subnet
    default: 192.0.2.0/24

  provision_net_ip_version:
    type: number
    description: IP version for the provision_net subnet
    default: 4

  provision_net_shared:
    type: boolean
    description: Whether this network should be shared across all tenants
    default: false

  public_net:
    type: string
    description: Name of the overcloud external network
    default: public

  public_net_cidr:
    type: string
    description: CIDR for external network subnet
    default: 10.0.0.0/24

  public_net_allocation_pools:
    type: comma_delimited_list
    description: Allocation Pools for the public network
    default: []

  public_subnet_ip_version:
    type: number
    description: IP version for the public subnet
    default: 4

  public_net_shared:
    type: boolean
    description: Whether this network should be shared across all tenants
    default: false


outputs:
  networks:
    value:
      provision: {get_param: provision_net}
      public: {get_param: public_net}
  # The provision and public network routers is here for compatibility only
  provision_network_routers:
    value: null
  public_network_router:
    value: null
